name: Publish

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
  - cron: '0 0 * * *'

env:
  CARGO_TERM_COLOR: always

jobs:
  main:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - run: "sudo apt-get install -y cmark pandoc texlive-full"
    - uses: actions/checkout@v2
    - run: "git submodule init"
    - run: "git submodule update"
    - run: "./art/fonts/build"
    - uses: actions/upload-artifact@v3
      with:
        name: fonts.html
        path: art/fonts/view.html
    - uses: actions/upload-pages-artifact@v2
