name: Publish

on:
  workflow_dispatch:
  push:
    branches: [ master ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - run: "sudo apt-get install -y cmark pandoc texlive-full"
    - uses: actions/checkout@v2
    - run: "git submodule init"
    - run: "git submodule update"
    - run: "./art/fonts/build"
    - run: "mkdir pages"
    - run: "cp index.html pages"
    - run: "cp art/fonts/darkdown.css pages"
    - run: "cp art/fonts/view.html pages/fonts.html"
    - uses: actions/upload-pages-artifact@v2
      with:
        path: pages
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: deployment
        uses: actions/deploy-pages@v2
