name: Publish

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
  - cron: '0 0 * * *'

env:
  CARGO_TERM_COLOR: always

jobs:
  main:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - run: "sudo apt-get install -y cmark pandoc texlive-full"
    - uses: actions/checkout@v2
    - run: "git submodule init"
    - run: "git submodule update"
    - run: "./art/fonts/build"
    - run: "cp -f art/fonts/view.html fonts.html"
    - run: "tar -cvf github-pages.tar fonts.html"
    - run: "gzip -9 github-pages.tar"
    - uses: actions/upload-artifact@v3
      with:
        name: github-pages
        path: github-pages.tar.gz
    - uses: actions/upload-pages-artifact@v2
